AllCops:
  Exclude:
    - config/**/*
    - db/**/*
    - bin/*
    - vendor/**/*

MethodLength:
  Max: 10

ClassLength:
  Max: 100

Documentation:
  Enabled: false

LineLength:
  Max: 100

AbcSize:
  Max: 20
