development:
  adapter: postgresql
  encoding: unicode
  database: jetpack-api_development
  pool: 5
  username: jetpack-api
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: jetpack-api_test
  pool: 5
  username: jetpack-api
  password:

# Heroku is cool